[project]
name = "paper-meco-maps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.14",
    "cartogram>=1.0.0",
    "dotenv>=0.9.9",
    "duckdb>=1.4.3",
    "fiona>=1.10.1",
    "geopandas>=1.1.1",
    "ipykernel>=7.1.0",
    "mapbox>=0.18.1",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "pyarrow>=22.0.0",
    "seaborn>=0.13.2",
]
